#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Python-Bytecode
version:      2.6
version_from: Bytecode.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
